import type { PageData } from "./pages";

export const contractPages = {
  "about/history": {
    path: "/about/history", label: "发展历程", eyebrow: "OUR JOURNEY", title: "钜豪发展历程", seoTitle: "发展历程与品牌荣誉｜钜豪照明", image: "/images/juhao-industrial.webp",
    description: "查看钜豪照明2020年以来在渠道战略、智慧家庭、产品发布与行业荣誉方面的公开发展节点。",
    intro: "时间线依据企业知识库公司新闻整理，记录钜豪在照明、智慧家庭、产品与渠道协同方向的可追溯节点。",
    highlights: [{ title: "渠道共建", text: "以区域会议和经销商盛典持续连接合作伙伴。" }, { title: "智慧家庭", text: "2021年公开发布钜豪智慧家庭。" }, { title: "产品演进", text: "通过年度新品会议持续更新产品与方案。" }],
    sections: [{ title: "资料边界", text: "本页只采用可追溯的企业新闻节点；成立年份、产能、门店数量等未完成企业档案核验的口径不在此发布。" }],
    related: [{ label: "品牌介绍", href: "/about", text: "了解钜豪的品牌主张。" }, { label: "加入钜豪", href: "/about/join", text: "查看招聘信息发布原则。" }, { label: "联系钜豪", href: "/contact", text: "提交合作需求。" }],
  },
  "about/join": {
    path: "/about/join", label: "加入钜豪", eyebrow: "JOIN JUHAO", title: "与钜豪一起创造好光", seoTitle: "加入钜豪｜钜豪照明", image: "/images/juhao-commercial.webp", noindex: true,
    description: "钜豪照明招聘与人才页面。正式职位、地点与申请方式将在企业确认后发布。",
    intro: "我们重视对用户、空间和长期价值保持好奇的人。当前页面不发布未经企业确认的职位、待遇或联系方式。",
    highlights: [{ title: "产品与技术", text: "围绕照明与智能体验持续探索。" }, { title: "空间与设计", text: "把需求转译成清晰的光环境方案。" }, { title: "渠道与服务", text: "连接合作伙伴与真实用户。" }],
    sections: [{ title: "职位发布", text: "所有正式职位将标明职责、要求、工作地点与有效期；申请入口由企业确认后开放。" }],
    related: [{ label: "关于钜豪", href: "/about", text: "了解品牌与业务方向。" }, { label: "发展历程", href: "/about/history", text: "查看经核验的品牌节点。" }, { label: "新闻资讯", href: "/news", text: "了解近期内容。" }],
  },
  "solutions/hospitality": {
    path: "/solutions/hospitality", label: "酒店照明", eyebrow: "HOSPITALITY LIGHTING", title: "酒店照明解决方案", seoTitle: "酒店照明解决方案｜钜豪照明", image: "/images/juhao-home.webp", type: "service",
    description: "了解酒店抵达、公共区域、客房与餐饮空间的照明规划重点，并获取项目咨询入口。",
    intro: "酒店光环境需要在识别、氛围与休息之间自然转换，让宾客从抵达到入住都感受到连续而克制的空间体验。",
    highlights: [{ title: "抵达空间", text: "建立入口识别与欢迎感。" }, { title: "公共区域", text: "用层次串联通行、交流与停留。" }, { title: "客房", text: "支持阅读、休息与夜间起居。" }, { title: "餐饮", text: "兼顾食物显色与桌面氛围。" }],
    sections: [{ title: "从宾客旅程规划光", text: "先梳理抵达、登记、通行、停留与休息等关键行为，再确定亮度层次、色温感受和控制场景。" }, { title: "项目重点", text: "酒店照明还需兼顾运营时段、维护便利与不同空间之间的视觉连续性。", points: ["控制客房直视眩光", "强化导向与空间识别", "按运营时段设置场景", "考虑检修与更换便利"] }],
    related: [{ label: "商业照明", href: "/solutions/commercial", text: "查看商业空间的光环境思路。" }, { label: "健康光", href: "/healthy-light", text: "了解以人为中心的照明原则。" }, { label: "项目咨询", href: "/contact", text: "提交酒店类型与项目阶段。" }],
  },
  "healthy-light": {
    path: "/healthy-light", label: "健康光", eyebrow: "HUMAN-CENTRIC LIGHT", title: "让光更关照人的感受", seoTitle: "健康光环境｜钜豪照明", image: "/images/juhao-home.webp", type: "service",
    description: "从视觉舒适、显色、眩光、时间与场景等维度，了解钜豪健康光环境的规划思路。",
    intro: "健康光不是单一参数或口号，而是围绕人的活动、时间和空间条件，综合处理看清、舒适、氛围与控制。",
    highlights: [{ title: "视觉舒适", text: "在看清的同时控制直视眩光与强烈反差。" }, { title: "真实显色", text: "让人物、食物与材质呈现自然。" }, { title: "时间节奏", text: "让不同时间的亮度和色温更符合活动需要。" }, { title: "简单控制", text: "让高频场景容易使用，也能灵活调整。" }],
    sections: [{ title: "从人和活动开始", text: "先明确空间里的人要做什么、停留多久、视线在哪里，再选择灯具、配光与控制方式。" }, { title: "不夸大未经验证的指标", text: "产品级光学、光谱或健康声明必须由正式检测和企业资料支持；在数据接入前，本页只陈述通用规划原则。" }],
    related: [{ label: "全屋照明", href: "/solutions/residential", text: "把健康光原则应用到家庭空间。" }, { label: "酒店照明", href: "/solutions/hospitality", text: "查看旅居场景的光环境规划。" }, { label: "照明资讯", href: "/news", text: "阅读更多基础知识。" }],
  },
  "sustainability": {
    path: "/sustainability", label: "可持续发展", eyebrow: "SUSTAINABILITY", title: "让长期价值被看见", seoTitle: "可持续发展｜钜豪照明", image: "/images/juhao-public.webp", noindex: true,
    description: "了解钜豪照明可持续发展页面的信息框架，以及产品、运营、伙伴与社会责任方向的披露原则。",
    intro: "可持续发展需要可验证的数据与持续行动。本页面先建立披露框架，正式指标、报告与案例仅在企业核验后发布。",
    highlights: [{ title: "产品责任", text: "关注使用效率、耐久与可维护性。" }, { title: "运营责任", text: "用可验证数据呈现资源与运营改善。" }, { title: "伙伴协同", text: "与渠道和项目伙伴建立清晰责任边界。" }, { title: "透明披露", text: "区分目标、行动、结果与尚未完成事项。" }],
    sections: [{ title: "披露边界", text: "不使用未经审计的数字、不复制原站 ESG 成果，也不把行业目标描述成钜豪已经完成的事实。" }, { title: "后续内容", text: "经核验后可按年度发布报告、行动进展与案例，并保留资料下载和无障碍阅读版本。" }],
    related: [{ label: "健康光", href: "/healthy-light", text: "了解以人为中心的光环境原则。" }, { label: "资料下载", href: "/downloads", text: "查看已确认的公开资料。" }, { label: "关于钜豪", href: "/about", text: "了解品牌主张。" }],
  },
  "service": {
    path: "/service", label: "服务支持", eyebrow: "SERVICE & SUPPORT", title: "让每一次使用都有回应", seoTitle: "服务支持与服务网络｜钜豪照明", image: "/images/juhao-public.webp", type: "service",
    description: "查看钜豪照明总部服务、商城服务、工程项目支持、经销商协作、资料下载与常见问题入口。",
    intro: "从总部服务窗口到商城、工程与渠道协作，按真实业务类型进入对应服务路径。",
    highlights: [{ title: "总部服务", text: "通过公开热线和企业地址联系钜豪。" }, { title: "商城服务", text: "采购、订单和经销商业务由独立商城承接。" }, { title: "工程支持", text: "围绕项目阶段、方案和交付信息沟通。" }, { title: "资料支持", text: "集中管理经核验的产品与光学资料。" }],
    sections: [{ title: "服务流程", text: "准备产品型号、购买或项目资料、问题现象和所在城市，再进入对应服务入口。" }, { title: "服务网络", text: "当前公开总部、商城、工程与经销商协作四类服务入口；具体地区服务点将在地址与责任主体核验后逐步增加。" }],
    related: [{ label: "资料下载", href: "/downloads", text: "查看已确认的公开资料。" }, { label: "联系钜豪", href: "/contact", text: "提交方案或合作需求。" }, { label: "常见照明知识", href: "/news", text: "阅读使用与规划内容。" }],
    faqs: [{ question: "如何查询正式服务网点？", answer: "网点数据接入并经企业核验后，可按省市查询；当前不发布示例地址。" }, { question: "质保政策以什么为准？", answer: "以对应产品随附文件、购买凭证和企业正式公布的政策为准。" }],
  },
  "partners": {
    path: "/partners", label: "合作共创", eyebrow: "PARTNERSHIP", title: "与长期主义者一起成长", seoTitle: "经销商加盟与工程合作｜钜豪照明", image: "/images/juhao-commercial.webp", type: "service",
    description: "了解钜豪照明经销商合作、工程项目合作与供应商合作方向，以及合作流程和资料准备要求。",
    intro: "钜豪通过品牌官网承接合作咨询，以独立商城保留采购、订单与经销商业务能力。合作从区域、团队、服务能力和长期经营计划开始。",
    highlights: [{ title: "需求沟通", text: "说明区域、团队与业务方向。" }, { title: "能力评估", text: "共同评估服务、运营与交付条件。" }, { title: "方案确认", text: "明确边界、节奏与双方责任。" }, { title: "持续共建", text: "围绕用户与市场反馈持续优化。" }],
    sections: [{ title: "合作前可准备", text: "所在区域、现有团队、服务能力、业务经验与计划，是高效沟通的基础。" }, { title: "信息真实性", text: "本页不复制原站招商政策或联系人，也不承诺未经企业批准的区域权益。" }],
    related: [{ label: "钜豪商城", href: "/mall", text: "了解数字化渠道服务方向。" }, { label: "照明方案", href: "/solutions", text: "浏览主要业务场景。" }, { label: "联系合作", href: "/contact", text: "提交合作背景与方向。" }],
  },
  "downloads": {
    path: "/downloads", label: "资料下载", eyebrow: "DOWNLOADS", title: "产品与服务资料", seoTitle: "资料下载｜钜豪照明", image: "/images/juhao-industrial.webp", noindex: true,
    description: "钜豪照明资料下载中心。正式产品文档、软件与报告将在文件来源和版本核验后发布。",
    intro: "下载中心将按资料类型、适用产品、版本与更新时间组织文件。当前没有已核验文件，因此不提供示例下载链接。",
    highlights: [{ title: "产品资料", text: "规格、安装与使用文件。" }, { title: "软件工具", text: "标明系统、版本与校验信息。" }, { title: "品牌资料", text: "经授权的品牌与项目资料。" }, { title: "报告文件", text: "可持续或专题报告。" }],
    sections: [{ title: "文件发布标准", text: "每个文件必须包含名称、版本、适用范围、大小、更新时间与来源，失效文件及时下架。" }],
    related: [{ label: "服务支持", href: "/service", text: "查看常见问题与服务入口。" }, { label: "可持续发展", href: "/sustainability", text: "查看披露原则。" }, { label: "联系钜豪", href: "/contact", text: "咨询所需资料。" }],
  },
  "search": {
    path: "/search", label: "站内搜索", eyebrow: "SEARCH", title: "搜索钜豪网站", seoTitle: "站内搜索｜钜豪照明", image: "/images/juhao-home.webp", noindex: true,
    description: "搜索钜豪照明官网中的解决方案、服务与资讯内容。",
    intro: "输入关键词后，搜索结果将按页面、解决方案、资讯和资料分类展示。搜索结果页不进入搜索引擎索引。",
    highlights: [{ title: "页面", text: "品牌、服务与合作信息。" }, { title: "解决方案", text: "按空间查找光环境思路。" }, { title: "资讯", text: "查找照明知识与品牌内容。" }],
    sections: [{ title: "搜索状态", text: "阶段 5 将接入本地全文索引，并覆盖输入、加载、结果、空状态与错误状态。" }],
    related: [{ label: "照明方案", href: "/solutions", text: "按空间浏览。" }, { label: "新闻资讯", href: "/news", text: "阅读照明内容。" }, { label: "服务支持", href: "/service", text: "查看服务入口。" }],
  },
  "legal": {
    path: "/legal", label: "法律声明", eyebrow: "LEGAL", title: "法律声明", seoTitle: "法律声明｜钜豪照明", image: "/images/juhao-industrial.webp", noindex: true,
    description: "钜豪照明官网法律声明页面，正式文本将在法务审核后发布。",
    intro: "法律文本必须与实际运营主体、网站功能和数据处理方式一致。当前页面仅说明发布状态。",
    highlights: [{ title: "主体信息", text: "待企业与法务确认。" }, { title: "知识产权", text: "待结合公开内容与授权范围确认。" }, { title: "责任边界", text: "待结合网站功能审核。" }],
    sections: [{ title: "发布状态", text: "本页不复制原站法律文本。正式版本经企业法务审核后上线，并记录生效日期。" }],
    related: [{ label: "隐私政策", href: "/privacy", text: "查看隐私文本发布状态。" }, { label: "关于钜豪", href: "/about", text: "了解品牌。" }, { label: "联系钜豪", href: "/contact", text: "查看咨询入口。" }],
  },
  "privacy": {
    path: "/privacy", label: "隐私政策", eyebrow: "PRIVACY", title: "隐私政策", seoTitle: "隐私政策｜钜豪照明", image: "/images/juhao-public.webp", noindex: true,
    description: "钜豪照明官网隐私政策页面，正式文本将在数据流与功能确认后发布。",
    intro: "隐私政策必须准确对应网站实际收集、使用、保存和共享的数据。当前版本不作未经核验的承诺。",
    highlights: [{ title: "数据范围", text: "待搜索、表单与统计方案确认。" }, { title: "处理目的", text: "仅说明实际存在的处理活动。" }, { title: "用户权利", text: "待运营主体与联系渠道确认。" }],
    sections: [{ title: "发布状态", text: "正式版本将在功能和数据流完成审计后由企业审核，且不会沿用原站追踪脚本或隐私文本。" }],
    related: [{ label: "法律声明", href: "/legal", text: "查看法律文本发布状态。" }, { label: "服务支持", href: "/service", text: "查看服务入口。" }, { label: "联系钜豪", href: "/contact", text: "查看咨询入口。" }],
  },
} satisfies Record<string, PageData>;
