declare namespace Cloudflare {
  interface Env {
    DB?: D1Database;
    PUBLIC_INDEXING_ENABLED?: string;
    PUBLIC_INTAKE_READY?: string;
    NEXT_PUBLIC_TURNSTILE_SITE_KEY?: string;
    TURNSTILE_SECRET_KEY?: string;
    TURNSTILE_ALLOWED_HOSTNAMES?: string;
    CONTACT_EDGE_RATE_LIMIT_VERIFIED?: string;
    JUHAO_LEAD_RATE_LIMIT_SECRET?: string;
    JUHAO_LEAD_WEBHOOK_URL?: string;
    JUHAO_LEAD_WEBHOOK_SECRET?: string;
    JUHAO_LEAD_MAINTENANCE_SECRET?: string;
    NEXT_PUBLIC_PRIVACY_ANALYTICS_ENABLED?: string;
    PRIVACY_ANALYTICS_WRITE_ENABLED?: string;
    ANALYTICS_D1_MIGRATION_VERIFIED?: string;
    ANALYTICS_CLIENT_BUILD_VERIFIED?: string;
    ANALYTICS_EDGE_RATE_LIMIT_VERIFIED?: string;
    ANALYTICS_PRIVACY_APPROVED?: string;
  }
}
