// Generated by scripts/build_product_catalog.py --catalog-v2.
// The source of truth remains the frozen SQL and Obsidian snapshot.
import rawIndex from "./runtime/catalog-v2/index.json";
import rawManifest from "./runtime/catalog-v2/manifest.json";

export type CatalogV2FamilyIndex = {
  family_id: string;
  canonical_slug: string;
  canonical_source_key: string;
  canonical_source_id: string;
  topic_slug: string | null;
  planned_canonical_route: string | null;
  route_plan_state: "pending_category_selection" | "pending_topic_assignment" | "existing_route_preserved";
  route_plan_evidence: string;
  title: string;
  category: string;
  source_categories: string[];
  category_state: "source_category_unambiguous" | "pending_owner_selection";
  member_count: number;
  grouping_status: "auto_merged_shared_reference_image_set" | "singleton_unreviewed" | "human_approved_recategorize" | "human_approved_exclusion" | "human_approved_split" | "human_approved_merge";
  review_state: string;
  detail_state: string;
  detail_ref: string;
  model_label: string | null;
  model_state: string;
  model_evidence: string | null;
  series_label: string | null;
  series_state: string;
  representative: {
    source_key: string;
    display_id: string;
    title: string;
    primary_image: string | null;
  };
  variant_refs: Array<{
    source_key: string;
    source_id: string;
    display_id: string;
    model_label: string | null;
    model_state: string;
  }>;
  card_specs: Array<{
    key: string;
    label: string;
    values: string[];
    evidence: string;
  }>;
  facets: Record<string, string[]>;
  quality_flags: string[];
};

export type CatalogV2Variant = {
  variant_id: string;
  source_key: string;
  display_id: string;
  label: string;
  dimensions: Record<string, { value: string; evidence: string }>;
  normalized_specs: Array<{
    source_spec_code: string | null;
    source_row: number;
    normalization: string;
    weight: string | null;
    volume: string | null;
  }>;
  quality_flags: string[];
};

export type CatalogV2Detail = {
  schema_version: number;
  family: CatalogV2FamilyIndex;
  grouping_evidence: string;
  source_references: Array<{
    source_key: string;
    source_path: string;
    source_sha256: string;
  }>;
  representative_detail: {
    attributes: Record<string, string>;
    primary_image: string | null;
    detail_images: string[];
    detail_image_count: number;
    emitted_detail_image_count: number;
    suppressed_media_path_count: number;
    media_policy: string;
  };
  variants: CatalogV2Variant[];
  editorial_policy: {
    source_of_truth: string;
    product_body_copy: string;
    commercial_fields: string;
    manual_family_review_required: boolean;
    media_projection: string;
  };
};

export const catalogV2Index = rawIndex as {
  schema_version: number;
  snapshot_date: string;
  visibility: string;
  sample_size: number;
  items: CatalogV2FamilyIndex[];
};

export const catalogV2Manifest = rawManifest;

const detailLoaders: Record<
  string,
  () => Promise<{ default: unknown }>
> = {
  "family-77b9971e550c": () => import("./runtime/catalog-v2/details/family-77b9971e550c.json"),
  "family-5c97ea3f5b5b": () => import("./runtime/catalog-v2/details/family-5c97ea3f5b5b.json"),
  "family-7f75dcce796c": () => import("./runtime/catalog-v2/details/family-7f75dcce796c.json"),
  "family-972959f4c328": () => import("./runtime/catalog-v2/details/family-972959f4c328.json"),
  "family-c201aa392506": () => import("./runtime/catalog-v2/details/family-c201aa392506.json"),
  "family-dd0b539a1179": () => import("./runtime/catalog-v2/details/family-dd0b539a1179.json"),
  "family-907eecc820ae": () => import("./runtime/catalog-v2/details/family-907eecc820ae.json"),
  "family-3a66ceb9de0f": () => import("./runtime/catalog-v2/details/family-3a66ceb9de0f.json"),
  "family-a9891b9d18fa": () => import("./runtime/catalog-v2/details/family-a9891b9d18fa.json"),
  "family-606781f21fca": () => import("./runtime/catalog-v2/details/family-606781f21fca.json"),
  "family-91eba5983ab4": () => import("./runtime/catalog-v2/details/family-91eba5983ab4.json"),
  "family-db235d89122b": () => import("./runtime/catalog-v2/details/family-db235d89122b.json"),
  "family-18bd9bbbdcd2": () => import("./runtime/catalog-v2/details/family-18bd9bbbdcd2.json"),
  "family-f294d2abb5d4": () => import("./runtime/catalog-v2/details/family-f294d2abb5d4.json"),
  "family-559d77c8ac4e": () => import("./runtime/catalog-v2/details/family-559d77c8ac4e.json"),
  "family-b1164a806916": () => import("./runtime/catalog-v2/details/family-b1164a806916.json"),
  "family-2997a4ff9dfb": () => import("./runtime/catalog-v2/details/family-2997a4ff9dfb.json"),
  "family-15de95ee9cb2": () => import("./runtime/catalog-v2/details/family-15de95ee9cb2.json"),
  "family-1dd9feab2188": () => import("./runtime/catalog-v2/details/family-1dd9feab2188.json"),
  "family-a3d872de3600": () => import("./runtime/catalog-v2/details/family-a3d872de3600.json"),
  "family-0f78e49f6810": () => import("./runtime/catalog-v2/details/family-0f78e49f6810.json"),
  "family-5ae1d7b4ce39": () => import("./runtime/catalog-v2/details/family-5ae1d7b4ce39.json"),
  "family-0478937ccabe": () => import("./runtime/catalog-v2/details/family-0478937ccabe.json"),
  "family-1d589c134190": () => import("./runtime/catalog-v2/details/family-1d589c134190.json"),
  "family-0141cae86006": () => import("./runtime/catalog-v2/details/family-0141cae86006.json"),
  "family-26cb40005942": () => import("./runtime/catalog-v2/details/family-26cb40005942.json"),
  "family-05e3ae8cb530": () => import("./runtime/catalog-v2/details/family-05e3ae8cb530.json"),
  "family-00ad440b82ad": () => import("./runtime/catalog-v2/details/family-00ad440b82ad.json"),
  "family-40f624a702a7": () => import("./runtime/catalog-v2/details/family-40f624a702a7.json"),
  "family-2854de3594bb": () => import("./runtime/catalog-v2/details/family-2854de3594bb.json"),
  "family-01a94610353f": () => import("./runtime/catalog-v2/details/family-01a94610353f.json"),
  "family-0bdca7c5cf2f": () => import("./runtime/catalog-v2/details/family-0bdca7c5cf2f.json"),
  "family-ea384bf6c039": () => import("./runtime/catalog-v2/details/family-ea384bf6c039.json"),
  "family-a8351ce02e03": () => import("./runtime/catalog-v2/details/family-a8351ce02e03.json"),
  "family-8961b5141acf": () => import("./runtime/catalog-v2/details/family-8961b5141acf.json"),
  "family-073c5f520744": () => import("./runtime/catalog-v2/details/family-073c5f520744.json"),
  "family-47f8467d879d": () => import("./runtime/catalog-v2/details/family-47f8467d879d.json"),
  "family-47e2e8c76332": () => import("./runtime/catalog-v2/details/family-47e2e8c76332.json"),
  "family-60c5b5a0ae71": () => import("./runtime/catalog-v2/details/family-60c5b5a0ae71.json"),
  "family-191a63f0f13e": () => import("./runtime/catalog-v2/details/family-191a63f0f13e.json"),
  "family-0c71e863f0a7": () => import("./runtime/catalog-v2/details/family-0c71e863f0a7.json"),
  "family-484d28c6632a": () => import("./runtime/catalog-v2/details/family-484d28c6632a.json"),
  "family-70e95c590dd7": () => import("./runtime/catalog-v2/details/family-70e95c590dd7.json"),
  "family-2e55b4627a3d": () => import("./runtime/catalog-v2/details/family-2e55b4627a3d.json"),
  "family-b4fb65bf33b5": () => import("./runtime/catalog-v2/details/family-b4fb65bf33b5.json"),
  "family-063d0244168c": () => import("./runtime/catalog-v2/details/family-063d0244168c.json"),
  "family-05119a0ed4f5": () => import("./runtime/catalog-v2/details/family-05119a0ed4f5.json"),
  "family-247677a1e1db": () => import("./runtime/catalog-v2/details/family-247677a1e1db.json"),
  "family-63309f648a35": () => import("./runtime/catalog-v2/details/family-63309f648a35.json"),
  "family-0c5c64ffbde7": () => import("./runtime/catalog-v2/details/family-0c5c64ffbde7.json"),
  "family-121126e624cd": () => import("./runtime/catalog-v2/details/family-121126e624cd.json"),
  "family-09770a6aa8e5": () => import("./runtime/catalog-v2/details/family-09770a6aa8e5.json"),
  "family-8b5dfef55c9b": () => import("./runtime/catalog-v2/details/family-8b5dfef55c9b.json"),
  "family-91d441f42646": () => import("./runtime/catalog-v2/details/family-91d441f42646.json"),
  "family-0af5b0942f50": () => import("./runtime/catalog-v2/details/family-0af5b0942f50.json"),
  "family-259930bcc84a": () => import("./runtime/catalog-v2/details/family-259930bcc84a.json"),
  "family-3355b8346c45": () => import("./runtime/catalog-v2/details/family-3355b8346c45.json"),
  "family-00141a3f73aa": () => import("./runtime/catalog-v2/details/family-00141a3f73aa.json"),
  "family-e486585214ca": () => import("./runtime/catalog-v2/details/family-e486585214ca.json"),
  "family-6007c6330c54": () => import("./runtime/catalog-v2/details/family-6007c6330c54.json"),
  "family-8c41ab7e0a94": () => import("./runtime/catalog-v2/details/family-8c41ab7e0a94.json"),
  "family-58fca1a8dc11": () => import("./runtime/catalog-v2/details/family-58fca1a8dc11.json"),
  "family-881585d9a48c": () => import("./runtime/catalog-v2/details/family-881585d9a48c.json"),
  "family-1ab8d0abe8d0": () => import("./runtime/catalog-v2/details/family-1ab8d0abe8d0.json"),
  "family-1a45836a6951": () => import("./runtime/catalog-v2/details/family-1a45836a6951.json"),
  "family-5eb90bbb3cb2": () => import("./runtime/catalog-v2/details/family-5eb90bbb3cb2.json"),
  "family-82c3a2f750f6": () => import("./runtime/catalog-v2/details/family-82c3a2f750f6.json"),
  "family-964e1d823791": () => import("./runtime/catalog-v2/details/family-964e1d823791.json"),
  "family-d13d7302cb66": () => import("./runtime/catalog-v2/details/family-d13d7302cb66.json"),
  "family-621bb0e61753": () => import("./runtime/catalog-v2/details/family-621bb0e61753.json"),
  "family-05aa338dad9e": () => import("./runtime/catalog-v2/details/family-05aa338dad9e.json"),
  "family-2f5f4d6b67ac": () => import("./runtime/catalog-v2/details/family-2f5f4d6b67ac.json"),
  "family-9e78b941514d": () => import("./runtime/catalog-v2/details/family-9e78b941514d.json"),
  "family-1213fab175cf": () => import("./runtime/catalog-v2/details/family-1213fab175cf.json"),
  "family-17dd46c579a8": () => import("./runtime/catalog-v2/details/family-17dd46c579a8.json"),
  "family-1069690ed7d4": () => import("./runtime/catalog-v2/details/family-1069690ed7d4.json"),
  "family-a377b8fe54c8": () => import("./runtime/catalog-v2/details/family-a377b8fe54c8.json"),
  "family-b31735d3f77d": () => import("./runtime/catalog-v2/details/family-b31735d3f77d.json"),
  "family-0cbed20d7d08": () => import("./runtime/catalog-v2/details/family-0cbed20d7d08.json"),
  "family-2d4d9221c3e0": () => import("./runtime/catalog-v2/details/family-2d4d9221c3e0.json"),
  "family-424dd24463d8": () => import("./runtime/catalog-v2/details/family-424dd24463d8.json"),
  "family-0f67c1cbdb18": () => import("./runtime/catalog-v2/details/family-0f67c1cbdb18.json"),
  "family-3ededc1b34d4": () => import("./runtime/catalog-v2/details/family-3ededc1b34d4.json"),
  "family-0df081bdfae8": () => import("./runtime/catalog-v2/details/family-0df081bdfae8.json"),
  "family-91b5d42b6810": () => import("./runtime/catalog-v2/details/family-91b5d42b6810.json"),
  "family-6cd13aa020f0": () => import("./runtime/catalog-v2/details/family-6cd13aa020f0.json"),
  "family-bd737860eb7b": () => import("./runtime/catalog-v2/details/family-bd737860eb7b.json"),
  "family-de80a245138e": () => import("./runtime/catalog-v2/details/family-de80a245138e.json"),
  "family-3b173614a55a": () => import("./runtime/catalog-v2/details/family-3b173614a55a.json"),
  "family-9ca2739bb5a4": () => import("./runtime/catalog-v2/details/family-9ca2739bb5a4.json"),
  "family-c2b715cdac89": () => import("./runtime/catalog-v2/details/family-c2b715cdac89.json"),
  "family-cc3f07e6adf7": () => import("./runtime/catalog-v2/details/family-cc3f07e6adf7.json"),
  "family-e1dab7feab86": () => import("./runtime/catalog-v2/details/family-e1dab7feab86.json"),
  "family-09c6ca467068": () => import("./runtime/catalog-v2/details/family-09c6ca467068.json"),
  "family-37514617d37e": () => import("./runtime/catalog-v2/details/family-37514617d37e.json"),
  "family-f3350f14d9be": () => import("./runtime/catalog-v2/details/family-f3350f14d9be.json"),
  "family-1ce6adb924f9": () => import("./runtime/catalog-v2/details/family-1ce6adb924f9.json"),
  "family-2241fc4c6d86": () => import("./runtime/catalog-v2/details/family-2241fc4c6d86.json"),
  "family-12530a2dfe1d": () => import("./runtime/catalog-v2/details/family-12530a2dfe1d.json"),
  "family-f3df578f113f": () => import("./runtime/catalog-v2/details/family-f3df578f113f.json"),
  "family-dde6afc769f8": () => import("./runtime/catalog-v2/details/family-dde6afc769f8.json"),
  "family-102177fbe229": () => import("./runtime/catalog-v2/details/family-102177fbe229.json"),
  "family-5a7a617f4ec0": () => import("./runtime/catalog-v2/details/family-5a7a617f4ec0.json"),
  "family-76a48ec4846a": () => import("./runtime/catalog-v2/details/family-76a48ec4846a.json"),
  "family-2b73ba912284": () => import("./runtime/catalog-v2/details/family-2b73ba912284.json"),
  "family-5c280cb60b7d": () => import("./runtime/catalog-v2/details/family-5c280cb60b7d.json"),
  "family-50b4b4258de7": () => import("./runtime/catalog-v2/details/family-50b4b4258de7.json"),
  "family-92095fde724c": () => import("./runtime/catalog-v2/details/family-92095fde724c.json"),
  "family-bd62e8df3e0e": () => import("./runtime/catalog-v2/details/family-bd62e8df3e0e.json"),
  "family-d9a430f2bdc8": () => import("./runtime/catalog-v2/details/family-d9a430f2bdc8.json"),
  "family-007886dd3bb1": () => import("./runtime/catalog-v2/details/family-007886dd3bb1.json"),
  "family-66e803146e83": () => import("./runtime/catalog-v2/details/family-66e803146e83.json"),
  "family-aefe28b1d864": () => import("./runtime/catalog-v2/details/family-aefe28b1d864.json"),
  "family-ed3766a8fb3d": () => import("./runtime/catalog-v2/details/family-ed3766a8fb3d.json"),
  "family-0ae564ab2420": () => import("./runtime/catalog-v2/details/family-0ae564ab2420.json"),
  "family-668def5b4464": () => import("./runtime/catalog-v2/details/family-668def5b4464.json"),
  "family-1719f2e948dc": () => import("./runtime/catalog-v2/details/family-1719f2e948dc.json"),
  "family-24505804f4d8": () => import("./runtime/catalog-v2/details/family-24505804f4d8.json"),
  "family-229fd96a604a": () => import("./runtime/catalog-v2/details/family-229fd96a604a.json"),
  "family-217186202313": () => import("./runtime/catalog-v2/details/family-217186202313.json"),
};

export const catalogV2FamilyIds = Object.freeze(Object.keys(detailLoaders));

export async function catalogV2DetailById(familyId: string) {
  const loader = detailLoaders[familyId];
  return loader ? ((await loader()).default as CatalogV2Detail) : null;
}
