import type { PageData } from "@/app/_data/pages";
import { topicGuideBySlug } from "@/content/topic-guides";

export const productTopics = [
  { slug: "spotlights", title: "射灯与轨道照明", count: 10, scene: "重点照明", description: "面向住宅、酒店与商业空间的重点照明，以光束角、配光、防眩和安装条件为选型起点。", image: "/images/juhao-commercial.webp" },
  { slug: "ceiling-lights", title: "家居顶灯", count: 10, scene: "家庭基础照明", description: "覆盖客餐厅、卧室与辅助空间的基础照明，关注空间尺度、显色、清洁维护与控制方式。", image: "/images/juhao-home.webp" },
  { slug: "new-chinese", title: "新中式", count: 10, scene: "风格照明", description: "将东方尺度、材质与空间秩序融入灯饰表达，适用于住宅、会所与酒店空间。", image: "/images/juhao-hero.webp" },
  { slug: "art-lights", title: "艺术灯", count: 10, scene: "装饰照明", description: "以造型、材质与光影关系参与空间表达，产品资料将按型号和项目适配性逐步开放。", image: "/images/juhao-hero.webp" },
  { slug: "crystal-chandeliers", title: "水晶吊灯", count: 10, scene: "酒店与宴会", description: "面向挑高大堂、宴会厅与高端住宅，重点核对尺寸、承重、安装与维护条件。", image: "/images/juhao-commercial.webp" },
  { slug: "linear-lighting", title: "灯带与线性照明", count: 10, scene: "轮廓与氛围", description: "用于空间轮廓、间接照明与连续引导，选型同时考虑光效、色温、驱动与安装节点。", image: "/images/juhao-public.webp" },
  { slug: "switches", title: "开关电工", count: 10, scene: "空间控制", description: "连接照明回路与日常使用，关注负载、接线、面板组合及与智能场景的协同。", image: "/images/juhao-industrial.webp" },
  { slug: "outdoor-lighting", title: "户外照明", count: 10, scene: "建筑与景观", description: "服务建筑立面、道路与景观空间，需结合防护等级、配光、环境条件与维护方式选型。", image: "/images/juhao-public.webp" },
  { slug: "project-custom", title: "工程定制", count: 10, scene: "非标与项目", description: "围绕项目空间、造型、结构、安装和交付条件开展定制沟通，不以标准商品页替代工程确认。", image: "/images/juhao-commercial.webp" },
  { slug: "smart-home-devices", title: "家居智能设备", count: 10, scene: "场景联动", description: "覆盖照明控制与空间联动设备，正式选型需核对协议、兼容范围、部署与售后条件。", image: "/images/juhao-home.webp" },
] as const;

export type ProductTopic = (typeof productTopics)[number];

export const caseStudies = [
  {
    slug: "jw-marriott-shenzhen-huafa-snow-world", sourceId: "226", title: "深圳华发冰雪世界 JW 万豪酒店", type: "酒店照明", stage: "签约 / 中标项目", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c7439f6e3e8.png",
    summary: "围绕高端酒店的公共区域、宴会会议、餐饮休闲与客房场景，规划连续而有层次的光环境。",
    background: "项目位于深圳华发冰雪世界综合体，酒店空间涵盖抵达、社交、会议、餐饮、休闲与住宿等多种使用场景。",
    strategy: ["以公共区域的空间层次建立抵达体验", "为宴会与会议空间预留多场景照明", "兼顾餐饮氛围、客房休憩与阅读需求"],
    solutionScope: ["大堂与大堂吧", "宴会与会议空间", "餐饮与休闲区域", "客房照明"],
    productList: ["定制装饰灯具", "重点照明灯具", "线性与间接照明", "客房壁灯及阅读灯"],
    confirmedFacts: ["企业知识库文章 226 记录钜豪照明中标该项目", "企业资料将项目定位为深圳华发冰雪世界综合体的酒店配套", "现有方案范围覆盖公共区域、宴会会议、餐饮休闲与客房", "本页图片均按方案效果资料呈现，不作为完工实拍"],
    completionEvidence: ["完工实景图：待项目组补充", "最终产品型号清单：待项目组确认", "调试与验收记录：待补充"],
    spaceBreakdown: [
      { title: "公共区域", text: "资料把大堂、大堂吧与走廊列入方案范围，方向是通过灯饰与层次组织抵达和通行体验。" },
      { title: "宴会与会议", text: "资料提出兼顾商务会议与宴会庆典的多状态需求，具体控制场景与参数待项目最终资料确认。" },
      { title: "餐饮与休闲", text: "西餐厅、中餐厅、泳池和 SPA 被列入方案场景，现阶段只呈现光环境方向。" },
      { title: "客房", text: "资料提出休憩与阅读两类使用任务，最终灯具、控制和交付结果仍待补齐。" },
    ],
    relatedTopics: [
      { label: "射灯与轨道照明", href: "/products/spotlights" },
      { label: "灯带与线性照明", href: "/products/linear-lighting" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "酒店照明方案", href: "/solutions/hospitality" },
    evidenceLabel: "中标新闻与空间方案图，不作为完工证明",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c743ad43839.png", width: 800, height: 450, alt: "深圳华发冰雪世界 JW 万豪酒店建筑方案效果图", caption: "建筑方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c743db9106a.jpg", width: 800, height: 999, alt: "深圳华发冰雪世界 JW 万豪酒店公共区域方案效果图", caption: "公共区域方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c743ffd2a5a.jpg", width: 800, height: 897, alt: "深圳华发冰雪世界 JW 万豪酒店大堂吧方案效果图", caption: "大堂吧方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c7442c89978.png", width: 800, height: 362, alt: "深圳华发冰雪世界 JW 万豪酒店宴会会议空间方案效果图", caption: "宴会会议空间方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c7443952e8a.jpg", width: 800, height: 400, alt: "深圳华发冰雪世界 JW 万豪酒店餐饮空间方案效果图", caption: "餐饮空间方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c744424aa21.jpg", width: 800, height: 771, alt: "深圳华发冰雪世界 JW 万豪酒店休闲空间方案效果图", caption: "休闲空间方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c7444d27e39.jpg", width: 800, height: 862, alt: "深圳华发冰雪世界 JW 万豪酒店客房方案效果图", caption: "客房方案效果图｜企业知识库文章 226｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-03/69c744570ca6f.jpg", width: 800, height: 837, alt: "深圳华发冰雪世界 JW 万豪酒店客房阅读区域方案效果图", caption: "客房阅读区域方案效果图｜企业知识库文章 226｜非完工实拍" },
    ],
  },
  {
    slug: "pullman-shangrao-guangfeng", sourceId: "231", title: "上饶广丰铂尔曼酒店", type: "酒店照明", stage: "签约 / 中标项目", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a15460fa0817.jpg",
    summary: "以东方空间语汇组织大堂、餐厅、宴会与客房的照明层次，服务不同功能与停留节奏。",
    background: "项目为上饶广丰的五星级酒店项目，资料显示照明范围涉及大堂、餐饮、宴会与客房等核心区域。",
    strategy: ["用线性与重点照明梳理大堂结构", "兼顾餐饮空间的社交属性与桌面体验", "以分层布光支持宴会与客房的不同状态"],
    solutionScope: ["酒店大堂", "全日餐厅", "宴会厅", "客房区域"],
    productList: ["线性格栅灯", "嵌入式重点照明", "壁灯与装饰灯具", "水晶吊灯及间接照明"],
    confirmedFacts: ["企业知识库文章 231 记录钜豪照明中标该项目", "企业资料将项目描述为上饶广丰的五星级酒店项目", "现有方案范围覆盖大堂、餐饮、宴会与客房", "本页图片均按设计方案效果资料呈现，不作为完工实拍"],
    completionEvidence: ["现有图片为项目方案资料", "完工实景图：待项目组补充", "最终型号与数量清单：待确认"],
    spaceBreakdown: [
      { title: "大堂", text: "资料以线性照明、嵌入式光和壁灯组织屋顶结构、前台与公共区域层次。" },
      { title: "餐饮", text: "全日餐厅与中餐包房分别强调自然景观、桌面体验和装饰灯饰，均为方案描述。" },
      { title: "宴会", text: "资料提出水晶吊灯、线性灯带和不同活动状态，最终控制系统与型号清单待确认。" },
      { title: "客房", text: "资料以间接照明、床头灯和书桌任务光组织休息与办公场景，尚无完工验收资料。" },
    ],
    relatedTopics: [
      { label: "射灯与轨道照明", href: "/products/spotlights" },
      { label: "水晶吊灯", href: "/products/crystal-chandeliers" },
      { label: "灯带与线性照明", href: "/products/linear-lighting" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "酒店照明方案", href: "/solutions/hospitality" },
    evidenceLabel: "中标新闻与设计方案图，不作为完工证明",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a15461de56c3.jpg", width: 800, height: 484, alt: "上饶广丰铂尔曼酒店建筑方案效果图", caption: "建筑方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a15464ab6b2c.jpg", width: 800, height: 435, alt: "上饶广丰铂尔曼酒店大堂方案效果图", caption: "大堂方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a154689b2e77.jpg", width: 800, height: 441, alt: "上饶广丰铂尔曼酒店全日餐厅方案效果图", caption: "全日餐厅方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a1546a7a9670.jpg", width: 800, height: 640, alt: "上饶广丰铂尔曼酒店中餐包房方案效果图", caption: "中餐包房方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a1546c0e62ee.jpg", width: 800, height: 566, alt: "上饶广丰铂尔曼酒店宴会厅方案效果图", caption: "宴会厅方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a1546ce7a9bf.jpg", width: 800, height: 362, alt: "上饶广丰铂尔曼酒店宴会厅灯光方案效果图", caption: "宴会厅灯光方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a1546dccabec.jpg", width: 800, height: 474, alt: "上饶广丰铂尔曼酒店客房方案效果图", caption: "客房方案效果图｜企业知识库文章 231｜非完工实拍" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-05/6a1546ff9ef08.jpg", width: 800, height: 533, alt: "上饶广丰铂尔曼酒店客房阅读区域方案效果图", caption: "客房阅读区域方案效果图｜企业知识库文章 231｜非完工实拍" },
    ],
  },
  {
    slug: "grand-hyatt-suzhou-financial-street", sourceId: "228", title: "苏州金融街君悦酒店", type: "酒店照明", stage: "签约 / 中标项目", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b8c623027.jpg",
    summary: "企业知识库文章明确记录中标，并按八个空间分节描述方案方向；施工、供货、交付与完工状态仍待项目资料确认。",
    background: "来源文章记录该项目中标，并以大堂、大堂吧、餐饮、宴会与客房等八个明确分节介绍方案。页面只转述来源能够支持的阶段与空间方向。",
    strategy: ["逐项保留来源明确命名的八个空间分节", "将灯具与布光描述标记为方案方向而非落地结果", "最终型号、参数、控制系统与交付状态等待项目负责人签核"],
    solutionScope: ["大堂与大堂吧", "全日餐厅与中餐厅", "大宴会厅与小宴会厅", "嘉宾轩与客房"],
    productList: ["来源提及非标灯饰、射灯与线性灯", "来源提及吊灯、壁灯、台灯与落地灯", "最终采用型号、数量与控制清单：待项目组确认"],
    confirmedFacts: ["企业知识库文章 228 的标题明确记录中标", "文章来源日期为 2026-04-08", "来源正文含 23 张图片，并明确列出 8 个空间分节", "页面空间名称与方案方向均来自来源文字，不根据图片推断"],
    completionEvidence: ["施工、供货、交付与完工状态：待项目组确认", "最终产品型号、数量与控制系统：待补充", "项目验收资料：待补充", "封面与正文图的官网公开使用授权：待核验"],
    spaceBreakdown: [
      { title: "大堂", text: "来源将灯饰方案与苏州园林的梅枝疏影、江南烟雨意象关联；具体工艺与落地结果待确认。" },
      { title: "大堂吧", text: "来源描述以灯带、台灯、落地灯和壁灯组织分层照明；最终配置与实施状态待确认。" },
      { title: "全日餐厅", text: "来源描述暖色环境光、嵌入式射灯、小吊灯与壁灯的组合；参数和实际配置待确认。" },
      { title: "大宴会厅", text: "来源描述暖光基调、基础照明、环形水晶灯饰并提及调光；控制系统与实施状态待确认。" },
      { title: "小宴会厅", text: "来源描述分层布光与格栅吊灯方向；实际灯具、参数和场景设置待确认。" },
      { title: "中餐厅", text: "来源描述暖色温、线性灯、射灯与灯笼造型吊灯；实际配置与交付结果待确认。" },
      { title: "嘉宾轩", text: "来源描述线性灯、射灯、长条水晶吊灯和辅助灯具；最终采用清单待确认。" },
      { title: "客房", text: "来源描述吊灯、灯带、射灯及床头、台面和落地辅助灯具；实际配置待确认。" },
    ],
    relatedTopics: [
      { label: "射灯与轨道照明", href: "/products/spotlights" },
      { label: "水晶吊灯", href: "/products/crystal-chandeliers" },
      { label: "灯带与线性照明", href: "/products/linear-lighting" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "酒店照明方案", href: "/solutions/hospitality" },
    sourceMeta: { sourceDate: "2026-04-08", bodyImageCount: 23, factBoundary: "仅确认来源标题记录的中标阶段", mediaAuthorization: "封面与正文图公开使用授权待核验", spaceEvidenceNote: "来源正文明确提供 8 个空间分节。" },
    evidenceLabel: "中标来源与正文资料图，不作为施工、交付或完工证明；媒体授权待核验",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b8e1e5c72.jpg", alt: "苏州金融街君悦酒店正文资料图 02", caption: "企业知识库文章 228 正文图 02｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b8ffc883d.jpg", alt: "苏州金融街君悦酒店正文资料图 03", caption: "企业知识库文章 228 正文图 03｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b90d813d1.jpg", alt: "苏州金融街君悦酒店正文资料图 04", caption: "企业知识库文章 228 正文图 04｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b92e5d35d.jpg", alt: "苏州金融街君悦酒店正文资料图 05", caption: "企业知识库文章 228 正文图 05｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b94fdaff0.jpg", alt: "苏州金融街君悦酒店正文资料图 06", caption: "企业知识库文章 228 正文图 06｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b9633f20e.jpg", alt: "苏州金融街君悦酒店正文资料图 07", caption: "企业知识库文章 228 正文图 07｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b975e7ddd.jpg", alt: "苏州金融街君悦酒店正文资料图 08", caption: "企业知识库文章 228 正文图 08｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d5b988db2c3.jpg", alt: "苏州金融街君悦酒店正文资料图 09", caption: "企业知识库文章 228 正文图 09｜公开使用授权待核验" },
    ],
  },
  {
    slug: "doubletree-nantong-haimen", sourceId: "229", title: "南通海门希尔顿逸林酒店", type: "酒店照明", stage: "签约 / 中标项目", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89ab58183c.jpg",
    summary: "来源标题明确记录中标；文章含 11 张正文图，但没有可独立核对的空间分节，因此本页不按图片推断空间。",
    background: "企业知识库文章 229 记录钜豪照明中标该项目。来源没有提供明确空间分节，施工、供货、交付与完工状态均未确认。",
    strategy: ["只呈现来源明确记录的中标阶段", "不根据图片内容推断空间名称、用途或落地效果", "待项目负责人补充服务范围、产品清单与验收资料"],
    solutionScope: ["来源未提供可独立核对的空间分节", "具体服务范围：待项目负责人确认"],
    productList: ["最终产品型号与数量：待补充", "控制系统与调试范围：待补充", "不得根据图片推定已采用产品"],
    confirmedFacts: ["企业知识库文章 229 的标题明确记录中标", "文章来源日期为 2026-04-10", "来源正文含 11 张图片", "来源正文没有明确空间分节，本页不根据图片推断"],
    completionEvidence: ["空间与服务范围：待项目负责人确认", "施工、供货、交付与完工状态：待确认", "产品、调试与验收资料：待补充", "封面与正文图的官网公开使用授权：待核验"],
    spaceBreakdown: [],
    relatedTopics: [
      { label: "酒店照明产品", href: "/products/spotlights" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "酒店照明方案", href: "/solutions/hospitality" },
    sourceMeta: { sourceDate: "2026-04-10", bodyImageCount: 11, factBoundary: "仅确认来源标题记录的中标阶段", mediaAuthorization: "封面与正文图公开使用授权待核验", spaceEvidenceNote: "来源正文未提供明确空间分节，本页不根据图片内容推断空间名称或用途。" },
    evidenceLabel: "中标来源与正文资料图，不作为施工、交付或完工证明；媒体授权待核验",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89ad000e0b.jpg", alt: "南通海门希尔顿逸林酒店正文资料图 02", caption: "企业知识库文章 229 正文图 02｜不推断空间｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89ad8cfde7.jpg", alt: "南通海门希尔顿逸林酒店正文资料图 03", caption: "企业知识库文章 229 正文图 03｜不推断空间｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89aedece5a.jpg", alt: "南通海门希尔顿逸林酒店正文资料图 04", caption: "企业知识库文章 229 正文图 04｜不推断空间｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89b07ae27e.jpg", alt: "南通海门希尔顿逸林酒店正文资料图 05", caption: "企业知识库文章 229 正文图 05｜不推断空间｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2026-04/69d89b1e098b9.jpg", alt: "南通海门希尔顿逸林酒店正文资料图 06", caption: "企业知识库文章 229 正文图 06｜不推断空间｜公开使用授权待核验" },
    ],
  },
  {
    slug: "yangzhou-riverfront-lighting", sourceId: "220", title: "扬州经开区“一河两岸”户外亮化工程", type: "户外亮化", stage: "签约 / 中标项目", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2025-12/69392e5990867.png",
    summary: "来源标题明确记录中标，正文只有 4 张图片且没有明确空间分节；页面完整说明资料缺口，不重复图片补数量。",
    background: "企业知识库文章 220 记录钜豪照明中标该户外亮化工程。来源中的未来设想不作为已实施效果，当前尚不表述为完工案例。",
    strategy: ["只呈现来源明确记录的中标阶段", "不把来源中的未来设想改写为已完成效果", "待补充项目范围、控制、能耗、交付与验收资料"],
    solutionScope: ["来源未提供可独立核对的空间分节", "户外亮化具体范围：待项目负责人确认"],
    productList: ["最终产品型号与数量：待补充", "控制系统与能耗口径：待补充", "不得根据图片推定已采用产品"],
    confirmedFacts: ["企业知识库文章 220 的标题明确记录中标", "文章来源日期为 2025-12-10", "来源正文只有 4 张图片", "来源正文没有明确空间分节，本页不根据图片推断"],
    completionEvidence: ["具体项目范围与阶段：待负责人确认", "施工、交付、控制与能耗资料：待补充", "夜景完工与验收资料：待补充", "封面与正文图的官网公开使用授权：待核验"],
    spaceBreakdown: [],
    relatedTopics: [
      { label: "户外照明", href: "/products/outdoor-lighting" },
      { label: "灯带与线性照明", href: "/products/linear-lighting" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "公共照明方案", href: "/solutions/public" },
    sourceMeta: { sourceDate: "2025-12-10", bodyImageCount: 4, factBoundary: "仅确认来源标题记录的中标阶段", mediaAuthorization: "封面与正文图公开使用授权待核验", spaceEvidenceNote: "来源正文未提供明确空间分节，本页不根据图片内容推断空间名称或用途。" },
    evidenceLabel: "中标来源与 4 张正文资料图，不作为施工、交付或夜景完工证明；媒体授权待核验",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2025-12/69392e6d12085.png", alt: "扬州经开区一河两岸正文资料图 02", caption: "企业知识库文章 220 正文图 02｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2025-12/69392e9e84b11.jpg", alt: "扬州经开区一河两岸正文资料图 03", caption: "企业知识库文章 220 正文图 03｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2025-12/69392e93b7d52.jpg", alt: "扬州经开区一河两岸正文资料图 04", caption: "企业知识库文章 220 正文图 04｜公开使用授权待核验" },
    ],
  },
  {
    slug: "xingtai-financial-center", sourceId: "199", title: "邢台金融中心", type: "商业综合体", stage: "中标报道 / 助力口径", image: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5c9b74c25.jpg",
    summary: "来源标题使用“助力”，正文首段记录中标并称将提供照明解决方案；本页不将该口径升级为已供货、已交付或已完工。",
    background: "企业知识库文章 199 的标题使用“助力”，正文首段记录中标并使用将来时描述服务。来源明确列出八个空间分节，可用于呈现方案方向。",
    strategy: ["保留来源的中标报道与助力口径，不升级项目阶段", "逐项呈现来源明确命名的八个空间分节", "删除宣传判断，只保留可追溯的灯具与布光方向"],
    solutionScope: ["会议中心与多功能厅", "企业接待与贵宾接待空间", "酒店大堂与全日餐厅", "包厢与客房"],
    productList: ["来源提及平板灯与艺术吊灯方向", "来源提及玻璃吊灯、台灯、落地灯与灯带方向", "最终采用型号、数量、施工与控制清单：待项目组确认"],
    confirmedFacts: ["企业知识库文章 199 的标题使用助力口径，正文首段记录中标并称将提供方案", "文章来源日期为 2024-12-03", "来源正文含 15 张图片，并明确列出 8 个空间分节", "页面已移除需要独立核验的宣传判断"],
    completionEvidence: ["施工、供货、交付与完工状态：待项目组确认", "最终产品型号、数量与控制系统：待补充", "项目验收资料：待补充", "封面与正文图的官网公开使用授权：待核验"],
    spaceBreakdown: [
      { title: "会议中心门厅", text: "来源描述以建筑元素与太行文化为方案线索，并提及天花平板灯方向；实际配置待确认。" },
      { title: "多功能厅", text: "来源描述以太行花与井字形元素组织灯光方案；具体灯具、参数和落地状态待确认。" },
      { title: "企业接待中心门厅", text: "来源描述天花井字吊灯方向，并将其与建筑文化表达关联；实际配置待确认。" },
      { title: "酒店大堂", text: "来源描述艺术水晶吊灯及吧台吊灯方向；灯具规格、数量与落地结果待确认。" },
      { title: "全日餐厅", text: "来源描述玻璃吊灯与柔和照明方向；实际灯具与参数待确认。" },
      { title: "包厢", text: "来源描述新中式吊灯与暖色调吊灯方向；最终配置与实施状态待确认。" },
      { title: "贵宾接待室", text: "来源描述沙发旁台灯作为功能与装饰光源的方向；具体产品待确认。" },
      { title: "客房", text: "来源描述灯带、落地灯、台灯与床头小吊灯等辅助照明方向；实际配置待确认。" },
    ],
    relatedTopics: [
      { label: "艺术灯", href: "/products/art-lights" },
      { label: "水晶吊灯", href: "/products/crystal-chandeliers" },
      { label: "灯带与线性照明", href: "/products/linear-lighting" },
      { label: "工程定制", href: "/products/project-custom" },
    ],
    relatedSolution: { label: "商业照明方案", href: "/solutions/commercial" },
    sourceMeta: { sourceDate: "2024-12-03", bodyImageCount: 15, factBoundary: "仅保留来源的中标报道与助力口径", mediaAuthorization: "封面与正文图公开使用授权待核验", spaceEvidenceNote: "来源正文明确提供 8 个空间分节。" },
    evidenceLabel: "中标报道、助力口径与正文资料图，不作为供货、交付或完工证明；媒体授权待核验",
    evidenceImages: [
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5cb32535d.jpg", alt: "邢台金融中心正文资料图 02", caption: "企业知识库文章 199 正文图 02｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5cc476297.jpg", alt: "邢台金融中心正文资料图 03", caption: "企业知识库文章 199 正文图 03｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5cd8abff3.jpg", alt: "邢台金融中心正文资料图 04", caption: "企业知识库文章 199 正文图 04｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5cf347892.jpg", alt: "邢台金融中心正文资料图 05", caption: "企业知识库文章 199 正文图 05｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5d18983fe.jpg", alt: "邢台金融中心正文资料图 06", caption: "企业知识库文章 199 正文图 06｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5d2950211.jpg", alt: "邢台金融中心正文资料图 07", caption: "企业知识库文章 199 正文图 07｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5d39b5196.jpg", alt: "邢台金融中心正文资料图 08", caption: "企业知识库文章 199 正文图 08｜公开使用授权待核验" },
      { src: "https://bocang.oss-cn-shenzhen.aliyuncs.com/upload/image/2024-12/674e5d52c1eb2.jpg", alt: "邢台金融中心正文资料图 09", caption: "企业知识库文章 199 正文图 09｜公开使用授权待核验" },
    ],
  },
] as const;

export type CaseStudy = (typeof caseStudies)[number];

export function catalogPageData(routeKey: string): PageData | null {
  const topic = routeKey.startsWith("products/") ? productTopics.find((item) => `products/${item.slug}` === routeKey) : undefined;
  if (topic) {
    const guide = topicGuideBySlug(topic.slug);
    return {
    path: `/${routeKey}`, label: topic.title, eyebrow: "PRODUCT TOPIC", title: topic.title,
    seoTitle: `${topic.title}｜产品专题｜钜豪照明`, description: `${topic.description} 浏览钜豪照明${topic.title}专题与相关方案入口。`, image: topic.image,
    intro: topic.description, type: "page",
    highlights: [{ title: "按场景理解", text: topic.scene }, { title: "按参数核对", text: "型号、功率、尺寸、配光与安装条件需以正式资料为准。" }],
    sections: [{ title: "专题说明", text: topic.description }, { title: "发布规则", text: "产品详情按销售状态、图片、参数、事业部和资料完整性完成审核后逐步开放。" }],
    related: [{ label: "返回产品中心", href: "/products", text: "查看全部产品专题。" }, { label: "查看照明方案", href: "/solutions", text: "按空间场景理解选型方法。" }, { label: "咨询产品与方案", href: `/contact?source=product-topic&sourceDetail=${topic.slug}&scene=project&intent=project-brief`, text: "提交空间、阶段和需求。" }],
    ...(guide ? { faqs: guide.faqs } : {}),
    };
  }
  const study = routeKey.startsWith("cases/") ? caseStudies.find((item) => `cases/${item.slug}` === routeKey) : undefined;
  if (study) return {
    path: `/${routeKey}`, label: study.title, eyebrow: "PROJECT UPDATE", title: study.title,
    seoTitle: `${study.title}｜${study.stage}｜钜豪照明`, description: `${study.summary} 当前阶段：${study.stage}。`, image: study.image,
    intro: study.summary, type: "page",
    highlights: [{ title: "项目类型", text: study.type }, { title: "当前阶段", text: study.stage }, { title: "资料编号", text: `企业知识库文章 ${study.sourceId}` }],
    sections: [{ title: "项目背景", text: study.background }, { title: "照明策略", text: "现有项目资料形成以下方向；具体型号、参数与实施结果以项目最终资料为准。", points: [...study.strategy] }],
    related: [{ label: "返回工程案例", href: "/cases", text: "浏览酒店、商业与户外项目动态。" }, { label: study.relatedSolution.label, href: study.relatedSolution.href, text: "了解对应空间的照明方法。" }, { label: "提交工程需求", href: `/contact?source=case-detail&sourceDetail=${study.sourceId}&scene=project&intent=project-brief`, text: "从项目类型与阶段开始沟通。" }],
  };
  return null;
}
